index_route:
  path: /
  defaults:
    _controller: ApiBundle:Error:actionNotFound

user_login:
  path: /user/login
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:login

user_logout:
  path: /user/logout
  methods: [GET]
  defaults:
    _controller: ApiBundle:User:logout

user_change_pass:
  path: /user/change-password
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:changePass

user_get_info:
  path: /user/get-my-data
  methods: [GET]
  defaults:
    _controller: ApiBundle:User:getUserInfo

user_register:
  path: /user/register
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:register

user_change_data:
  path: /user/change-data
  methods: [POST]
  defaults:
    _controller: ApiBundle:User:changeData

user_get_offer_list:
  path: /user/get-offer-list
  methods: [GET]
  defaults:
    _controller: ApiBundle:User:getOfferList


brand_add:
  path: /brand/add
  methods: [POST]
  defaults:
    _controller: ApiBundle:Brand:add

brand_model_version:
  path: /brand-model-version
  methods: [GET]
  defaults:
    _controller: ApiBundle:Brand:getBrandModelVersion

offer_add:
  path: /offer/add
  methods: [POST]
  defaults:
    _controller: ApiBundle:Offer:add

offer_add_photo:
  path: /offer/{id}/add-photo
  methods: [POST]
  defaults:
    _controller: ApiBundle:Offer:addPhoto

offer_remove_photo:
  path: /offer/remove-photo/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Offer:removePhoto

offer_get_edit_data:
  path: /offer/get-edit-data/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Offer:getEditData

offer_get_offer:
  path: /offer/get-offer/{id}
  methods: [GET]
  defaults:
    _controller: ApiBundle:Offer:getOffer

offer_remove:
  path: /offer/remove/{id}
  methods: [DELETE]
  defaults:
    _controller: ApiBundle:Offer:removeOffer


offer_renew:
  path: /offer/renew/{id}
  methods: [POST]
  defaults:
    _controller: ApiBundle:Offer:renewOffer

offer_get-most-popular:
  path: /offer/popular
  methods: [GET]
  defaults:
    _controller: ApiBundle:Offer:getMostPopularOffers


equipment_get:
  path: /equipment/get
  methods: [GET]
  defaults:
    _controller: ApiBundle:Equipment:getEquipment

