services:
  phpass_service:
      class: ApiBundle\Service\PHPass
      arguments: [8, false]
  user_service:
    class: ApiBundle\Service\User
    arguments: [ "@doctrine.orm.entity_manager", "@phpass_service" ]
  brand_service:
    class: ApiBundle\Service\Brand
    arguments: [ "@doctrine.orm.entity_manager" ]
  model_service:
    class: ApiBundle\Service\Model
    arguments: [ "@doctrine.orm.entity_manager" ]
  version_service:
    class: ApiBundle\Service\Version
    arguments: [ "@doctrine.orm.entity_manager" ]
  offer_service:
    class: ApiBundle\Service\Offer
    arguments: [ "@doctrine.orm.entity_manager", "@user_service" ]
  equipment_service:
    class: ApiBundle\Service\Equipment
    arguments: [ "@doctrine.orm.entity_manager" ]
